"""create threat analyses table

Revision ID: 59e8f28a5c03
Revises: 71eef07d67a8
Create Date: 2026-08-12 14:17:43.185110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e8f28a5c03'
down_revision: Union[str, Sequence[str], None] = '71eef07d67a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('threat_score', sa.Float(), nullable=False),
    sa.Column('threat_level', sa.String(), nullable=False),
    sa.Column('abuse_confidence_score', sa.Integer(), nullable=False),
    sa.Column('abuse_total_reports', sa.Integer(), nullable=False),
    sa.Column('vt_malicious', sa.Integer(), nullable=False),
    sa.Column('vt_suspicious', sa.Integer(), nullable=False),
    sa.Column('vt_harmless', sa.Integer(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_analyses_id'), 'threat_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_threat_analyses_ip'), 'threat_analyses', ['ip'], unique=False)
    op.create_index(op.f('ix_threat_analyses_threat_level'), 'threat_analyses', ['threat_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_analyses_threat_level'), table_name='threat_analyses')
    op.drop_index(op.f('ix_threat_analyses_ip'), table_name='threat_analyses')
    op.drop_index(op.f('ix_threat_analyses_id'), table_name='threat_analyses')
    op.drop_table('threat_analyses')
    # ### end Alembic commands ###
